### PR TITLE
Feature: Shadow

### PR DESCRIPTION
**Pull request by vcwild**
Implement `in_shadow`

World now handles ambient shadows

### CODE REVIEW

**Comment by iaurg** [comment]
I've tried to figure out why test17 fails, but I only know that some values return -nan from comps:

```sh
comps->over_point->x = -nan 
comps->over_point->y = -nan 
comps->over_point->z = -nan 
comps->over_point->w = -nan 
comps->normalv->x = -nan 
comps->normalv->y = -nan 
comps->normalv->z = -nan 
comps->normalv->w = -nan
```

I'm testing function by function to see if there's a function error or a test misconfiguration.

image

Debugging code the error occurs inside get normal function when we try to normalize tmp_normal, maybe because we try to divide by 0?
image

With an if inside normaliize we solve the "-nan" problem in test, but test still not pass:
```c
t_tuple	*normalize(t_tuple *a)
{
	if (magnitude(a) == 0)
		return (multiply_scalar(a, 1.0));
	return (multiply_scalar(a, 1.0 / magnitude(a)));
}
```

**Comment by vcwild** [comment]
@iaurg I am investigating the same problem. When using `clang` compiler the program is working without nan attribution. Maybe there is some unhandled exception when casting from integer to float.

Also a later test using `in_shade` is using the over_point implementation, which is the only change after previous tests.

**Comment by iaurg** [comment]
> @iaurg I am investigating the same problem. When using `clang` compiler the program is working without nan attribution. Maybe there is some unhandled exception when casting from integer to float.
> 
> Also a later test using `in_shade` is using the over_point implementation, which is the only change after previous tests.

I thought about the same question, casting types, if I test printf with %d it works.

Maybe this exact combination of numbers produce a unexpected behavior?

**Comment by vcwild** [comment]
> > @iaurg I am investigating the same problem. When using `clang` compiler the program is working without nan attribution. Maybe there is some unhandled exception when casting from integer to float.
> > Also a later test using `in_shade` is using the over_point implementation, which is the only change after previous tests.
> 
> I thought about the same question, casting types, if I test printf with %d it works.
> 
> Maybe this exact combination of numbers produce a unexpected behavior?

I vouch to keep this test disabled and go back to it if it's needed, otherwise the implementation works and we can merge the PR.

**Pull request merged**
